### ISSUE TITLE
Joveler.Compression.ZLib.ZLibException: [StreamError]

### ISSUE THREAD

**Issue by Luzifix** [ied206/Joveler.Compression#4]
Hi i am currently having problems running the ZLib tests with .net5.0. Do you have any idea what the problem could be?

Error:

>   Fehler Compress [27 ms]
  Fehlermeldung:
   Test method Joveler.Compression.ZLib.Tests.DeflateStreamTests.Compress threw exception: 
Joveler.Compression.ZLib.ZLibException: [StreamError]
  Stapelverfolgung:
      at Joveler.Compression.ZLib.DeflateStream.Flush() in H:\Joveler.Compression-master\Joveler.Compression.ZLib\ZLibStreams.cs:line 527
   at Joveler.Compression.ZLib.DeflateStream.Dispose(Boolean disposing) in H:\Joveler.Compression-master\Joveler.Compression.ZLib\ZLibStreams.cs:line 253
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at Joveler.Compression.ZLib.Tests.DeflateStreamTests.CompressTemplate(String sampleFileName, ZLibCompLevel level, Boolean useSpan) in H:\Joveler.Compression-master\Joveler.Compression.ZLib.Tests\DeflateStreamTests.cs:line 88
   at Joveler.Compression.ZLib.Tests.DeflateStreamTests.Compress() in H:\Joveler.Compression-master\Joveler.Compression.ZLib.Tests\DeflateStreamTests.cs:line 41

Full test log: [Tests Log.txt](https://github.com/ied206/Joveler.Compression/files/6835428/Tests.Log.txt)

**Comment by Luzifix** [comment]
FYI: With .net core 3.1 and .net 4.8 everything works fine

**Comment by ied206** [comment]
This issue stems from `Write(ReadOnlySpan<byte> span)` call, but I cannot diagnose why it happens. 
Which version of .NET 5.0 SDK did you use to run the test?

**Comment by ied206** [comment]
Looking through the last CI build/tests, the test did succeed in the last versions of .NET 5.
- [AppVeyor](https://ci.appveyor.com/project/ied206/joveler-compression/branch/develop/job/18n4wby22kcm1pis#L113)

When did you update your .NET 5.0 SDK?

**Comment by Luzifix** [comment]
im currently use .NET SDK 5.0.302

**Comment by Luzifix** [comment]
It seems to be something with the 5.0.301/302 version. After i downgrade to 5.0.202 anything works fine

**Comment by ied206** [comment]
I submitted an issue to the .NET runtime repo. 

I highly suspect a bug of .NET runtime on [GCHandle pinning](https://devblogs.microsoft.com/dotnet/using-gc-efficiently-part-3/) handling. More info on dotnet/runtime#55944 issue.

**Comment by Luzifix** [comment]
thx i downgrade to 5.0.202 :)

**Comment by ied206** [comment]
The issue was resolved in latest .NET SDK 5.0.400.
